// <auto-generated />
namespace HaberAtolyesi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _07032023 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_07032023));
        
        string IMigrationMetadata.Id
        {
            get { return "202303071004557_07-03-2023"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
